# Generated by Django 4.1.2 on 2022-10-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('0', 'Escolha uma categoria'), ('1', 'Padaria'), ('2', 'Alimentos (cereais e grãos)'), ('3', 'Congelados e frios'), ('4', 'Hortifruti'), ('5', 'Produtos de limpeza'), ('6', 'Higiene pessoal'), ('7', 'Bebidas'), ('8', 'Papelaria')], default='0', max_length=1)),
                ('nome', models.CharField(max_length=20)),
                ('preco', models.FloatField()),
                ('marca', models.CharField(max_length=15)),
            ],
        ),
    ]
